// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZxD-lQx_YlcxxdRfEWdUlubL0gfDF2Y',
    appId: '1:101065303298:web:7250676516afc5f7f58e1b',
    messagingSenderId: '101065303298',
    projectId: 'auth-229b6',
    authDomain: 'auth-229b6.firebaseapp.com',
    storageBucket: 'auth-229b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-mJQC4BPwkwRfhY-BUJ0ALC_iOSowq-E',
    appId: '1:101065303298:android:97e04c13a0b40f61f58e1b',
    messagingSenderId: '101065303298',
    projectId: 'auth-229b6',
    storageBucket: 'auth-229b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzuk89VnN29Ag7WWUgscnOtRjA1adwgtw',
    appId: '1:101065303298:ios:3ce2fcb132f2b30bf58e1b',
    messagingSenderId: '101065303298',
    projectId: 'auth-229b6',
    storageBucket: 'auth-229b6.appspot.com',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzuk89VnN29Ag7WWUgscnOtRjA1adwgtw',
    appId: '1:101065303298:ios:4424ddf23a2a92aaf58e1b',
    messagingSenderId: '101065303298',
    projectId: 'auth-229b6',
    storageBucket: 'auth-229b6.appspot.com',
    iosBundleId: 'com.example.authProject.RunnerTests',
  );
}
